version: "3"

networks:
    vulnweb:
        external: true

services:

  server:
    container_name: server_master
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ../vulnweb/:/var/www/html
      - ./settings/server/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - api
    networks:
      - vulnweb

  api:
    container_name: server_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ../vulnweb/:/var/www/html
      - ./settings/server/php/php.ini:/usr/local/etc/php/php.ini   
    depends_on:
      - mongo
      - mysql
    networks:
      - vulnweb

  mongo:
    container_name: server_mongo
    restart: always
    image: mongo:3.4
    ports:
      - "27017:27017"
    networks:
      - vulnweb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - ./settings/server/mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js

  mysql:
      container_name: server_mysql
      restart: always
      command: --init-file /tmp/mysql/init.sql
      image: mysql
      ports:
        - "3306:3306"
      networks:
        - vulnweb
      volumes:
        - ./settings/server/mysql/init.sql:/tmp/mysql/init.sql
        - ./settings/server/mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      environment:
        MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${DB_NAME}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
